name: Publish Docker image

on:
  workflow_dispatch:
    
  push:
    branches: [ "master" ]
    paths-ignore:
      - "**/README.md"
      - "CONTRIBUTING.md "
      - "LICENSE"
      - ".github/workflows/**"
      - "manifest.json"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ID: ${{ github.run_number }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Export OpenVPN version to variable
        run: echo "OPENVPN_VERSION=$(cat version)" >> $GITHUB_ENV
        shell: bash

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mjl42/openvpn
          tags: |
            type=raw,value=${{ env.OPENVPN_VERSION }}
            type=raw,value=${{ env.OPENVPN_VERSION }}-build${{ env.BUILD_ID }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/master'
        with:
          tag_name: ${{ env.OPENVPN_VERSION }}-build${{ env.BUILD_ID }}
          generate_release_notes: true
